  
title: Gabriel Draxton # your name (or website title) here
 # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of the University of Colorado Boulder 
  with a Master of Science Busness Analytics (Security Track) Degree. 
  <br><br>
  Phone (719) 510-0005 
  Email: Gabriel.Draxton@colorado.edu
  <br><br>
  SKILLS: 
  Strong knowledge of 
  Microsoft Office, Python, Pyspark, 
  Rstudio, SQL, NoSQL, Tableau, Gephi, 
  Docker, Google Cloud Platform, PyTorch, 
  TensorFlow, Keras, scikit-learn, NumPy, 
  Pandas 
  <br><br>
  Strong knowledge of Marketing Decision 
  Science, Unstructured Data, Web Scraping, 
  Data Cleansing and Manipulation, Predictive 
  Modeling, Topic Modeling, Network Analysis, 
  Language Processing, and Statistics
  <br><br>
  <a href="Resume_Draxton_June_2021.pdf">View My Resume</a>
 
  <br><br>
  <a href="https://www.linkedin.com/in/gabrieldraxton/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
