  
title: Gabriel Draxton # your name (or website title) here
logo: "Profile Pic.jpg" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate of the University of Colorado Boulder 
  with a Master of Science Busness Analytics (Security Track) Degree. 
  <br><br>
  Phone (719) 510-0005 
  Email: Gabriel.Draxton@colorado.edu
  <br><br>
  <a href="Resume_Draxton_June_2021.pdf">View My Resume</a>
  <br><br>
  <a href="https://www.linkedin.com/in/gabrieldraxton/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
